# Drawdowns Exercise

In this notebook, I develop a function that allows Kindur's clients to learn how long their money can last under different market scenarios by running drawdown simulations. Let's import some of the necessary libraries first.

In [1]:
import os
import sys

os.chdir(os.path.join(os.path.expanduser('~'), 'src')) # this is where my github repo is cloned
import pandas as pd
import numpy as np

Assume that the client has the following investment portfolio

In [2]:
port_json = [{"type": "401k", "balance": 50000, "growthRate": 0.08},
             {"type": "ira", "balance": 100000, "growthRate": 0.06},
             {"type": "brokerage", "balance": 80000, "growthRate": 0.07},
             {"type": "rothIra", "balance": 20000, "growthRate": 0.05}
            ]
port_df = pd.DataFrame(port_json)
port_df.set_index('type', inplace=True)
port_df

           balance  growthRate
type
401k         50000        0.08
ira         100000        0.06
brokerage    80000        0.07
rothIra      20000        0.05

Given the above portfolio, we need to figure out how long the client's money will last assuming:

* They withdraw $20,000 at the beginning of each year
* They withdraw as much as possible from a single account and then withdraw the remainder from one other account
* The drawdown order is: brokerage, 401K, IRA, Roth IRA
* No taxes

This function `retire_portfolio_drawdown` will take `port_json` as an input as well as the drawdown order as defined as follows.

In [3]:
drawdown_order = ['brokerage', '401k', 'ira', 'rothIra']

In [4]:
def retire_portfolio_drawdown(port_json, drawdown_order, withdraw_per_year=20000):
    '''
    This function keeps track of a client's portfolio balances as she makes withdrawls over time
    while accounting for any investment growth that can still happen over time. It also will tell
    you how many years it will take for the client to run out of money
    
    Inputs:
        @param port_json: json with all the data that defines the client's investment portfolio
        @param drawdown_order: a list of the account types (as strings) that defines the order in which
            a client will drawdown the investment portfolio 
            must include: ['401k', 'ira', 'brokerage', 'rothira']
        @param withdraw_per_year: amount withdrawn at the beginning of year (20000 by default)
            
    Output:
        @param port_df_all: 
            a record of the balances over time for each account type (dataframe)
        @param total_balances:
            this is the array of balances in total at each point in time across all 
            accounts
        @param how_long:
            how long money will money last (scalar value)
    '''
    
    # validate inputs
    assert all(elem in drawdown_order  for elem in 
               ['brokerage', '401k', 'ira', 'rothIra']), "Invalid account type in drawdown_order"
    
    port_df = pd.DataFrame(port_json)
    assert all(elem in list(port_df.columns) for elem in ['type', 'balance', 
                                                          'growthRate']), 'Invalid keys in port_json'
    
    
    def balances_append(i, balances, acct_data, withdraw_per_year):
        # subroutine for tracking growth and withdrawals and append the updated balances accordingly
        # allows us to track as well when account gets overdrawn
        while True:
            new_balance = balances[i]*(1+np.asscalar(acct_data.growthRate.values)) - withdraw_per_year
            balances.append(new_balance)
    
            i = i + 1
            if balances[i] < 0:
                break
        return balances
    
    
    balances_dict = {}
    
    # loop through the account types in the order provided
    for acct_type in drawdown_order:
        
        acct_data = port_df.loc[port_df.type == acct_type]
        
        # initiate the balances
        if acct_type == drawdown_order[0]:
            balances = list(acct_data.balance - withdraw_per_year)
            i = 0
            balances = balances_append(i, balances, acct_data, withdraw_per_year)
        else: 
            # this is the record of balances from the previous account type that no longer has money
            # in it
            balances = prev_acct_balances.copy()
            
            for i in range(len(balances)):
                if prev_acct_balances[i] <= 0:
                    # if a balance is overdrawn from a previous account that was being withdrawn from, we
                    # need to start compensating with the balances in this account 
                    # (accounting for any year-by-year growth)
                    if i == 0:
                        balances[i] = np.asscalar(acct_data.balance) + prev_acct_balances[i]
                    else:
                        balances[i] = balances[i-1]*(1+np.asscalar(acct_data.growthRate)) + prev_acct_balances[i]
                else:
                    # otherwise we just need to keep track of the year-by-year growth in the balances of this account
                    if i == 0:
                        balances[i] = np.asscalar(acct_data.balance)
                    else:
                        balances[i] = balances[i-1]*(1+np.asscalar(acct_data.growthRate))

            i = len(balances)-1
            balances = balances_append(i, balances, acct_data, withdraw_per_year)
        
        balances_df = pd.DataFrame(balances, columns=acct_data.type, index=np.arange(1,len(balances)+1))
        balances_df.index.name = 'year_index'
        balances_dict[acct_type] = balances_df
    
        prev_acct_balances = balances
    
    df_all = pd.concat([balances_dict['brokerage'], balances_dict['401k'], balances_dict['ira'], 
                        balances_dict['rothIra']], axis=1)
    port_df_all = df_all.clip(lower=0) # replace all negative values with 0
    port_df_all = port_df_all.fillna(0) # replace all NaNs with 0
    
    total_balances = port_df_all.apply(sum, axis=1)
    how_long = total_balances.index.max()
    
    return port_df_all, total_balances, how_long

In [5]:
port_df_all, total_balances, how_long = retire_portfolio_drawdown(port_json=port_json, drawdown_order=drawdown_order)

Below, I report the balances year-by-year for each of the account types. I found this to be the most intuitive way to present the data as by assumption, the client withdraws as much as possible from a single account and then withdraws the remainder from one other account based on the drawdown order specified for the client. The year-by-year growth in each account must also be tracked.

In [6]:
port_df_all

type        brokerage          401k            ira       rothIra
year_index
1            60000.00  50000.000000  100000.000000  20000.000000
2            44200.00  54000.000000  106000.000000  21000.000000
3            27294.00  58320.000000  112360.000000  22050.000000
4             9204.58  62985.600000  119101.600000  23152.500000
5                0.00  57873.348600  126247.696000  24310.125000
6                0.00  42503.216488  133822.557760  25525.631250
7                0.00  25903.473807  141851.911226  26801.912813
8                0.00   7975.751712  150363.025899  28142.008453
9                0.00      0.000000  147998.619302  29549.108876
10               0.00      0.000000  136878.536460  31026.564320
11               0.00      0.000000  125091.248647  32577.892536
12               0.00      0.000000  112596.723566  34206.787162
13               0.00      0.000000   99352.526980  35917.126520
14               0.00      0.000000   85313.678599  37712.982846
15               0.00      0.000000   70432.499315  39598.631989
16               0.00      0.000000   54658.449274  41578.563588
17               0.00      0.000000   37937.956230  43657.491768
18               0.00      0.000000   20214.233604  45840.366356
19               0.00      0.000000    1427.087620  48132.384674
20               0.00      0.000000       0.000000  32051.716785
21               0.00      0.000000       0.000000  13654.302624
22               0.00      0.000000       0.000000      0.000000

The array of total balances at each point in time across all account types is shown below

In [7]:
total_balances

year_index
1     230000.000000
2     225200.000000
3     220024.000000
4     214444.280000
5     208431.169600
6     201851.405498
7     194557.297845
8     186480.786064
9     177547.728177
10    167905.100779
11    157669.141183
12    146803.510728
13    135269.653501
14    123026.661445
15    110031.131304
16     96237.012862
17     81595.447998
18     66054.599960
19     49559.472294
20     32051.716785
21     13654.302624
22         0.000000
dtype: float64

How long does it take for the client to run out of money?

In [8]:
how_long

22

By the beginning of the 22nd year the client is out of money.

# Possible Extensions

* Account for taxes: Withdrawals from Roth IRAs and 401Ks are tax free if you are 59 and 1/2 or older. Withdrawals from Traditional IRAs and 401Ks get taxed as ordinary income. Withdrawals from brokerage accounts will need to account for capital gains taxes.
* Provide additional guidance on the amount to withdraw each year. Why 20K USD per year?. Are there other forms of retirement income that can help you make your money last longer? This money lasts 22 years. The customer may live longer than this time horizon in which case, they'll need the additional retirement income to make their money last.
* Need to adjust for inflation. Required expenses will tend to go up over time. 20K needed in the first year will be more than 20K in the 10th year of retirement. 
* Different scenarios for growth rate: Volatility of growth rates -> Monte Carlo simulation. Quantify the probability of running out of money before a pre-specified horizon based on tens of thousands of scenarios. Want a safe withdrawal rate.
* Based on an analysis of Monte Carlo simulations mentioned above, consider a dynamic withdrawal rate rule. Higher annual withdrawal rates when the market is performing well. Any excess here that you don't spend can be deposited into a safer money market account. Lower annual withdrawal rates when market performance is poor. You can use the excess money you deposited into a money market account early on as a cushion for years when withdrawal rates are lower. 
* Optimization based on drawdown order: Stochastic linear program. Maximize amount of time the money will last but subject to constraints on desired minimum lifestyle each year and include penalty parameter that incorporates risk-aversion to especially bad performance (expected shortfall). Can choose any account to drawdown from at the start of the year (instead of having to withdraw as much as possible from one account and withdraw the remainder from one other account.